### ISSUE TITLE
copy explaining how to check for SSL cert

### ISSUE THREAD

**Issue by jpyuda** [18F/vote-gov#39]
Short copy explaining to users how to determine whether or not a site has a valid government-signed SSL cert (not all sites use https, but vote.gov will, so let's go with it)

Depending on where things land with usability testing, we may need to tailor this to a user's browser context (different instructions for desktop vs. mobile, for example). But for now let's start with something generic.

@kategarklavs please update this with your progress and move to "review" if appropriate

**Comment by kategarklavs** [comment]
@jpyuda Hello! I met with Eric last week and created this short description based on our convo:

https://docs.google.com/a/gsa.gov/document/d/1I1CAC85ezVM9paue4UmtAvyKw0hFoZ_gcPFP_wCzbW0/edit?usp=sharing

Eric recommended *against* mentioning https because not all gov sites have it. My thought is that we might inadvertently communicate that sites w/o https might not be trustworthy, even though that's not the case. (Happy to discuss further, too.)

**Comment by kategarklavs** [comment]
(Also, I can't seem to update the In progress > Review, but this is ready for Review)

**Comment by jpyuda** [comment]
I think let's add a paragraph beyond what you have there that says something to the effect of "this site is also protected by an SSL certificate, signed by the U.S. government" (and a short explanation of how to verify that?)

**Comment by kategarklavs** [comment]
@jpyuda On it! Should be ready by tomorrow, but I'll let you know if the process takes longer.

**Comment by kategarklavs** [comment]
@jpyuda OK — added a short bit about SSL certs, and I also shared this copy with my critique group to get their take on whether the second paragraph could use more explanation. This should be wrapped up by EOD!

**Comment by kategarklavs** [comment]
Update! After getting awesome feedback from my critique group, I've made additional updates to this description. (The description is a bit longer than I'd like, but I think the length is necessary, given the complexity of what we're trying to convey.)

Unless there are objections, I think this is ready for review by the larger team.

cc @jpyuda
